kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-custom-appconfig
  namespace: rhdh-operator
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config.yaml: |
    permission:
      enabled: true
      rbac:
        policies-csv-file: /opt/app-root/src/rbac/rbac-policies.csv
        conditionalPoliciesFile: /opt/app-root/src/rbac/rbac-conditional-policies.yaml
        policyFileReload: true
        includeTransitiveGroupOwnership: true
        admin:
          users:
            - name: group:default/rhdh-admins
        pluginsWithPermission:
          - catalog
          - scaffolder
          - permission
          - kubernetes
          - topology
          - techdocs
          - gitlab
          - adoption-insights
          - extensions
          - search

    extensions:
      installation:
        enabled: true

    app:
      baseUrl: ${APP_BASE_URL}
    signInPage: gitlab

    catalog:
      providers:
        gitlab:
          gitlabProvider:
            host: ${GITLAB_HOST}
            orgEnabled: true
            rules:
              - allow: [Group, User]
            schedule:
              frequency: { seconds: 60 }
              timeout: { seconds: 60 }

    auth:
      environment: production
      providers:
        gitlab:
          production:
            clientId: ${GITLAB_CLIENT_ID}
            clientSecret: ${GITLAB_CLIENT_SECRET}
            audience: ${GITLAB_AUDIENCE}
            callbackUrl: ${GITLAB_CALLBACK_URL}
            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName

    integrations:
      gitlab:
        - apiBaseUrl: ${GITLAB_API_BASE_URL}
          baseUrl: ${GITLAB_BASE_URL}
          host: ${GITLAB_HOST}
          token: ${GITLAB_TOKEN}

    backend:
      baseUrl: ${APP_BASE_URL}
      cors:
        origin: ${APP_BASE_URL}

    techRadar:
      url: ${TECHRADAR_URL}
    scaffolder:
      actions:
        allowed:
          - fetch:template
          - publish:file
          - debug:wait
          - debug:log
