apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-dynamic-plugins
  namespace: rhdh-operator
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
      - /dynamic-plugins-root/dynamic-plugins.extensions.yaml
    plugins:
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
