apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditions-cm
  namespace: rhdh-operator
data:
  rbac-conditional-policies.yaml: |
    ---
    # Developers: own entities + always readable kinds
    result: CONDITIONAL
    roleEntityRef: role:default/developers
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
    conditions:
      anyOf:
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims:
              - "$ownerRefs"
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - User
              - Group
              - Template

    ---
    # Administrators: full access to all catalog kinds
    result: CONDITIONAL
    roleEntityRef: role:default/administrators
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
      - delete
    conditions:
      anyOf:
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - Component
              - API
              - Resource
              - System
              - Domain
              - Template
              - Location
              - User
              - Group
