apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditions-cm
  namespace: rhdh-operator
data:
  rbac-conditional-policies.yaml: |
    # Scope: developers' access to catalog entities
    result: CONDITIONAL
    roleEntityRef: role:default/developers
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
    conditions:
      anyOf:
        # Owners: user or any of the user's groups listed in $ownerRefs
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims: ["$ownerRefs"]

        # All User and Group entities are readable in this POC
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds: ["User", "Group"]
