apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditions-cm
  namespace: rhdh-operator
data:
  rbac-conditional-policies.yaml: |
    result: CONDITIONAL
    roleEntityRef: role:default/developers
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
    conditions:
      anyOf:
        # Owned entities: read and update when the user or their groups are owners
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims: ["$ownerRefs"]

        # Always readable kinds for this POC
        # Users and Groups are readable, and Templates are readable so devs can see the Create page
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds: ["User", "Group", "Template"]
