apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.name }}
  description: Demo component scaffolded from local skeleton
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
