apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: default
  name: developers
  annotations:
    rbac.target: 'group:default/developers'
spec:
  type: team
  profile:
    displayName: Developers
  children: []
